name: Build John the Ripper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git build-essential autoconf libssl-dev libnss3-dev libkrb5-dev libgmp-dev libz-dev libbz2-dev python3 libpcap-dev

      - name: Clone John repo
        run: |
          git clone https://github.com/openwall/john.git john-the-ripper --depth=1

      - name: Configure Build
        run: |
          cd john-the-ripper/src
          ./configure

      - name: Build John the Ripper
        run: |
          cd john-the-ripper/src
          make -s -j$(nproc)

      - name: Check build result
        run: |
          cd john-the-ripper/run
          if [ -f "./john" ]; then
            echo "Build succeeded!"
            ./john --test
          else
            echo "Build failed!"
            exit 1
          fi

      - name: Zip the build
        run: zip -r john-the-ripper.zip john-the-ripper/run

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: john-the-ripper
          files: john-the-ripper.zip
          make_latest: true